### ISSUE TITLE
Python? Django?

### ISSUE THREAD

**Issue by nikodrupal** [volodkindv/epf_82_to_81#1]
Здравствуйте!
Сразу хочу извиниться, что пишу вам в гитхаб в issue.
Я ищу разработчика с опытом в Python (который у вас есть, судя по репозиторию :), хотя бы небольшим опытом в Django, возможностью разговаривать хотя бы на ломаном английском и суммарным опытом программирования от 2 до 100 лет :)
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (это именно скайп), если это про вас :)
Спасибо

**Comment by volodkindv** [comment]
Добрый день!
Увы, опыта в Django у меня нет. К тому же у меня есть основная работа, которую я не смогу совмещать с вашими задачами.
Да и код данного проекта ужасен чуть более чем полностью, так что ваше предложение не про меня ))
